### ISSUE TITLE
Event loop is closed error

### ISSUE THREAD

**Issue by martkir** [im-n1/karpet#3]
Hi,

Cool repo! 

I was just checking out some of the functionality in the "test_karpet.py" module. In particular the "test_fetch_news()" function. The function seems to work in the sense that it returns output. However, it terminates with a "event loop is closed error" (I have attached a screenshot). Do you know what could be causing this error?

Btw looking forward to your Reddit implementation!

![event loop error](https://user-images.githubusercontent.com/44242554/92629059-a5a8be80-f2c5-11ea-8dd4-4cdc7c5d1154.PNG)

**Comment by im-n1** [comment]
Ancient issue. Closing for now.
